use_frameworks!

platform :ios, '8.0'

target 'KWPublicUISDK_Example' do
  pod 'KWPublicUISDK', :path => '../'

  target 'KWPublicUISDK_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
