use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:GithubXkw1573/PublicSpecs.git'

platform :ios, '8.0'

target 'KWPublicUISDK_Example' do
  pod 'KWPublicUISDK', :path => '../'

  target 'KWPublicUISDK_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
